// This file has been automatically generated by gen_deployment.
// Do not make manual modifications there or they will be lost.

#ifndef __POK_KERNEL_GENERATED_DEPLOYMENT_H_
#define __POK_KERNEL_GENERATED_DEPLOYMENT_H_

#include <core/schedvalues.h>

#define POK_CONFIG_NB_LOCKOBJECTS 1
#define POK_CONFIG_NB_PARTITIONS 2
#define POK_CONFIG_NB_PROCESSORS 1
#define POK_CONFIG_NB_THREADS 14
#define POK_CONFIG_PARTITIONS_NLOCKOBJECTS                                     \
  { 1, 0 }
#define POK_CONFIG_PARTITIONS_NTHREADS                                         \
  { 7, 5 }
//thread scheduler
#define POK_CONFIG_PARTITIONS_SCHEDULER                                        \
  { POK_SCHED_PRIORITY, POK_SCHED_STATIC }
//partition scheduler
#define POK_CONFIG_SCHEDULER_FOR_PARTITIONS POK_SCHED_RR

#define POK_CONFIG_PARTITIONS_SIZE                                             \
  { 133120, 133120 }
#define POK_CONFIG_PROCESSOR_AFFINITY                                          \
  { 1, 1 }
#define POK_CONFIG_PROGRAM_NAME                                                \
  { "pr1/pr1.elf", "pr2/pr2.elf" }
#define POK_CONFIG_SCHEDULING_MAJOR_FRAME 73752000000
#define POK_CONFIG_SCHEDULING_NBSLOTS 2
#define POK_CONFIG_SCHEDULING_SLOTS                                            \
  { 36876000000, 36876000000}
#define POK_CONFIG_SCHEDULING_SLOTS_ALLOCATION                                 \
  { 0, 1 }

#define POK_CONFIG_PARTITIONS_PRIORITY \
   {                                   \
      1, 2                           \
   }
#define POK_CONFIG_PARTITIONS_PERIOD \
   {                                 \
      20, 20                         \
   }
#define POK_CONFIG_PARTITIONS_DEADLINE \
   {                                   \
      10, 20                           \
   }
#define POK_CONFIG_PARTITIONS_WEIGHT \
   {                                 \
      3, 4                           \
   }

#define POK_NEEDS_CONSOLE 1
#define POK_NEEDS_DEBUG 1
#define POK_NEEDS_LOCKOBJECTS 1
#define POK_NEEDS_SCHED_STATIC 1
#define POK_NEEDS_THREAD_SLEEP 1
#define POK_NEEDS_THREAD_SUSPEND 1
#define POK_NEEDS_TIME 1



typedef enum {
  pok_part_identifier_pr1 = 0,
  pok_part_identifier_pr2 = 1
} pok_part_identifiers_t;

typedef enum { pok_part_id_pr1 = 0, pok_part_id_pr2 = 1 } pok_part_id_t;

typedef enum { pok_nodes_node1 = 0 } pok_node_id_t;

#endif // __POK_KERNEL_GENERATED_DEPLOYMENT_H_
